### ISSUE TITLE
GCP research

### ISSUE THREAD

**Issue by masterandrey** [rabbit72/cloud_storage_budget#1]
Learn current investigation results from
https://github.com/pavlov-tony/xproject/issues/2

On [wiki page](https://github.com/rabbit72/cloud_storage_budget/wiki/Collecting-project-budget-data-from-GCP-%28Google-Cloud-platform%29) (in English)
that would summarize the research

**Comment by ValeriaShestakova** [comment]
We chose CSV-file for data report
