### ISSUE TITLE
User manual draft

### ISSUE THREAD

**Issue by masterandrey** [rabbit72/cloud_storage_budget#12]
Page on with and link from root page.

At first - just how to set up csv for AWS and GCP

Just draft - do it quick and close the task.
Perfect is not expected and not necessary.

**Comment by rabbit72** [comment]
I have added a page with instructions for AWS
https://github.com/rabbit72/cloud_storage_budget/wiki/How-to-create-CSV-report-on-AWS

**Comment by ValeriaShestakova** [comment]
And page with instructions for GCP:
https://github.com/rabbit72/cloud_storage_budget/wiki/How-to-create-CSV-report-on-GCP.
Links on these instructions added to home page.
