### ISSUE TITLE
AWS research

### ISSUE THREAD

**Issue by masterandrey** [rabbit72/cloud_storage_budget#2]
Learn current investigation results from
https://github.com/pavlov-tony/xproject/issues/3

On [wiki page](https://github.com/rabbit72/cloud_storage_budget/wiki/Collecting-project-budget-data-from-AWS-%28Amazon%29) (in English)
that would summarize the research

**Comment by rabbit72** [comment]
@masterandrey I have done the first version. Should I change anything in it?

**Comment by rabbit72** [comment]
We have stopped on .csv reports. We are using them.
