### ISSUE TITLE
Create app stub that get charges data from Amazon CloudWatch

### ISSUE THREAD

**Issue by masterandrey** [rabbit72/cloud_storage_budget#4]
Just boiler-plate - get token, call api and print result

**Comment by rabbit72** [comment]
I take it

**Comment by masterandrey** [comment]
add to README.md steps to get API token and to run the app

**Comment by masterandrey** [comment]
@rabbit72 please assign it to you and add contributors to the GitHub project so others could do the same with their tasks

**Comment by rabbit72** [comment]
I created the wiki page for this https://github.com/rabbit72/cloud_storage_budget/wiki/%5BAWS%5D-SDK-for-Python-(boto3)

**Comment by masterandrey** [comment]
No tests

**Comment by masterandrey** [comment]
And I the instruction with broken link
https://github.com/rabbit72/cloud_storage_budget/issues/13
So I cannot use it

**Comment by rabbit72** [comment]
I have added tests for AWS s3 and config.ini
