### ISSUE TITLE
Implementation description

### ISSUE THREAD

**Issue by masterandrey** [rabbit72/cloud_storage_budget#9]
Update page https://github.com/rabbit72/cloud_storage_budget/wiki/Widget with short description of our approach for the task.
For example that we are going to use tags to distinguish the projects.

With specific list of columns that we are going to use in ML (resource type, amount, cost, time etc).

**Comment by ValeriaShestakova** [comment]
I added information to widget. Is this OK?

**Comment by masterandrey** [comment]
nice work thank you
